module Yield
  module SDK
    module Order
      type order_create_params = {
        customer_id: String,
        total_amount: money_like,
        ?note: String?,
      }

      class OrderCreatePayload
        def self.build: (order_create_params) -> Hash[Symbol, Object?]
      end
    end
  end
end
